from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from rag.query import get_answer

app = FastAPI()

class QueryRequest(BaseModel):
    question: str

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def home():
    return {"message": "AI Assistant API Running"}

@app.post("/ask")
def ask_question(req: QueryRequest):
    """
    Receives a question and returns an answer generated by the AI assistant.
    """
    answer = get_answer(req.question)
    return {"answer": answer}
